// Language name lookup — supports both ISO 639-1 (2-letter) and ISO 639-2 (3-letter) codes.
// Tab format: "NATIVE-STUDY" e.g. "RU-EN" or "RUS-ENG"
// If a code is not found in the map, the raw code is returned as-is.

const LANG_MAP = {
  // ISO 639-1 (2-letter)
  AF: 'Afrikaans',
  AR: 'Arabic',
  AZ: 'Azerbaijani',
  BE: 'Belarusian',
  BG: 'Bulgarian',
  BN: 'Bengali',
  BS: 'Bosnian',
  CA: 'Catalan',
  CS: 'Czech',
  CY: 'Welsh',
  DA: 'Danish',
  DE: 'German',
  EL: 'Greek',
  EN: 'English',
  EO: 'Esperanto',
  ES: 'Spanish',
  ET: 'Estonian',
  EU: 'Basque',
  FA: 'Persian',
  FI: 'Finnish',
  FR: 'French',
  GA: 'Irish',
  GL: 'Galician',
  GU: 'Gujarati',
  HE: 'Hebrew',
  HI: 'Hindi',
  HR: 'Croatian',
  HU: 'Hungarian',
  HY: 'Armenian',
  ID: 'Indonesian',
  IS: 'Icelandic',
  IT: 'Italian',
  JA: 'Japanese',
  KA: 'Georgian',
  KK: 'Kazakh',
  KM: 'Khmer',
  KN: 'Kannada',
  KO: 'Korean',
  KY: 'Kyrgyz',
  LT: 'Lithuanian',
  LV: 'Latvian',
  MK: 'Macedonian',
  ML: 'Malayalam',
  MN: 'Mongolian',
  MR: 'Marathi',
  MS: 'Malay',
  MT: 'Maltese',
  MY: 'Burmese',
  NE: 'Nepali',
  NL: 'Dutch',
  NO: 'Norwegian',
  PA: 'Punjabi',
  PL: 'Polish',
  PS: 'Pashto',
  PT: 'Portuguese',
  RO: 'Romanian',
  RU: 'Russian',
  SI: 'Sinhala',
  SK: 'Slovak',
  SL: 'Slovenian',
  SQ: 'Albanian',
  SR: 'Serbian',
  SV: 'Swedish',
  SW: 'Swahili',
  TA: 'Tamil',
  TE: 'Telugu',
  TH: 'Thai',
  TL: 'Filipino',
  TR: 'Turkish',
  UK: 'Ukrainian',
  UR: 'Urdu',
  UZ: 'Uzbek',
  VI: 'Vietnamese',
  YI: 'Yiddish',
  ZH: 'Chinese',
  ZU: 'Zulu',

  // ISO 639-2 (3-letter)
  AFR: 'Afrikaans',
  ARA: 'Arabic',
  AZE: 'Azerbaijani',
  BEL: 'Belarusian',
  BUL: 'Bulgarian',
  BEN: 'Bengali',
  BOS: 'Bosnian',
  CAT: 'Catalan',
  CES: 'Czech',
  CYM: 'Welsh',
  DAN: 'Danish',
  DEU: 'German',
  ELL: 'Greek',
  ENG: 'English',
  EPO: 'Esperanto',
  SPA: 'Spanish',
  EST: 'Estonian',
  EUS: 'Basque',
  FAS: 'Persian',
  FIN: 'Finnish',
  FRA: 'French',
  GLE: 'Irish',
  GLG: 'Galician',
  GUJ: 'Gujarati',
  HEB: 'Hebrew',
  HIN: 'Hindi',
  HRV: 'Croatian',
  HUN: 'Hungarian',
  HYE: 'Armenian',
  IND: 'Indonesian',
  ISL: 'Icelandic',
  ITA: 'Italian',
  JPN: 'Japanese',
  KAT: 'Georgian',
  KAZ: 'Kazakh',
  KHM: 'Khmer',
  KAN: 'Kannada',
  KOR: 'Korean',
  KIR: 'Kyrgyz',
  LIT: 'Lithuanian',
  LAV: 'Latvian',
  MKD: 'Macedonian',
  MAL: 'Malayalam',
  MON: 'Mongolian',
  MAR: 'Marathi',
  MSA: 'Malay',
  MLT: 'Maltese',
  MYA: 'Burmese',
  NEP: 'Nepali',
  NLD: 'Dutch',
  NOR: 'Norwegian',
  PAN: 'Punjabi',
  POL: 'Polish',
  PUS: 'Pashto',
  POR: 'Portuguese',
  RON: 'Romanian',
  RUS: 'Russian',
  SIN: 'Sinhala',
  SLK: 'Slovak',
  SLV: 'Slovenian',
  SQI: 'Albanian',
  SRP: 'Serbian',
  SWE: 'Swedish',
  SWA: 'Swahili',
  TAM: 'Tamil',
  TEL: 'Telugu',
  THA: 'Thai',
  FIL: 'Filipino',
  TUR: 'Turkish',
  UKR: 'Ukrainian',
  URD: 'Urdu',
  UZB: 'Uzbek',
  VIE: 'Vietnamese',
  YID: 'Yiddish',
  ZHO: 'Chinese',
  ZUL: 'Zulu',
  // Fun extras
  TLH: 'Klingon',
  JBO: 'Lojban',
  ENG_OLD: 'Old English',
  LAT: 'Latin',
}

// Returns the full language name for a code, or the code itself if not found.
export function langName(code) {
  if (!code) return ''
  return LANG_MAP[code.toUpperCase()] ?? code
}

// Parse a tab name like "RU-EN" or "RUS-ENG" into [studyName, nativeName]
export function parseLangLabel(tab) {
  if (!tab) return ['', '']
  const parts = tab.split('-')
  if (parts.length < 2) return [tab, '']
  const study = langName(parts[1])
  const native = langName(parts[0])
  return [study, native]
}
